/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checkout_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a checkout session
         * @description Initializes a new checkout session from items and (optionally) buyer and fulfillment info.
         *     MUST return 201 with a rich, authoritative cart state.
         *
         *     Agents MAY include `affiliate_attribution` with `touchpoint: "first"` to record first-touch attribution.
         *     This enables multi-touch attribution models where networks can capture both first and last touch.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        /**
         * Retrieve a checkout session
         * @description Returns the latest authoritative state for the checkout session.
         */
        get: operations["getCheckoutSession"];
        put?: never;
        /**
         * Update a checkout session
         * @description Applies changes (items, fulfillment address, fulfillment option) and returns an updated authoritative cart state.
         */
        post: operations["updateCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}/complete": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a checkout session
         * @description Finalizes the checkout by applying a payment method. MUST create an order and return completed state on success.
         *
         *     Agents MAY include `affiliate_attribution` to ensure the merchant receives final attribution context.
         *     Attribution is stored alongside the resulting order but not returned in the response.
         */
        post: operations["completeCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}/cancel": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a checkout session
         * @description Cancels a session if not already completed or canceled.
         *     Agents MAY include an intent_trace to communicate why the session is being abandoned.
         */
        post: operations["cancelCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            name: string;
            line_one: string;
            line_two?: string;
            city: string;
            state: string;
            country: string;
            postal_code: string;
        };
        /** @description Context about where the attribution originated. */
        AffiliateAttributionSource: {
            /**
             * @description The type of attribution source.
             * @enum {string}
             */
            type: "url" | "platform" | "unknown";
            /**
             * Format: uri
             * @description Canonical content URL when type is 'url'.
             */
            url?: string;
        };
        /**
         * @description Flat key/value map for additional non-sensitive context.
         *     Keys must be strings; values must be strings, numbers, or booleans.
         *     Arrays and nested objects are NOT permitted.
         */
        AffiliateAttributionMetadata: {
            [key: string]: string | number | boolean;
        };
        /**
         * @description Optional affiliate attribution data for crediting third-party publishers.
         *     Write-only: not returned in responses. See RFC: Affiliate Attribution.
         *
         *     Forward compatibility: Servers SHOULD ignore unknown fields to support future extensions (per RFC §8.2).
         */
        AffiliateAttribution: {
            /** @description Identifier for the attribution provider / affiliate network namespace (e.g., 'impact.com'). */
            provider: string;
            /** @description Opaque provider-issued token for fraud-resistant validation. Treat as secret. */
            token?: string;
            /** @description Provider-scoped affiliate/publisher identifier. Required if token is omitted. */
            publisher_id?: string;
            /** @description Provider-scoped campaign identifier. */
            campaign_id?: string;
            /** @description Provider-scoped creative identifier. */
            creative_id?: string;
            /** @description Provider-scoped sub-tracking identifier. */
            sub_id?: string;
            source?: components["schemas"]["AffiliateAttributionSource"];
            /**
             * Format: date-time
             * @description RFC3339 timestamp when the attribution token was issued.
             */
            issued_at?: string;
            /**
             * Format: date-time
             * @description RFC3339 timestamp when the attribution token expires.
             */
            expires_at?: string;
            metadata?: components["schemas"]["AffiliateAttributionMetadata"];
            /**
             * @description Attribution touchpoint type. Use 'first' when capturing at session creation,
             *     'last' when capturing at completion. Enables multi-touch attribution models.
             * @enum {string}
             */
            touchpoint?: "first" | "last";
        } | unknown | unknown;
        FulfillmentDetails: {
            name?: string;
            phone_number?: string;
            /** Format: email */
            email?: string;
            address?: components["schemas"]["Address"];
        };
        Buyer: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            phone_number?: string;
        };
        Item: {
            id: string;
            quantity: number;
        };
        Disclosure: {
            /** @enum {string} */
            type: "disclaimer";
            /** @enum {string} */
            content_type: "plain" | "markdown";
            content: string;
        };
        CustomAttribute: {
            display_name: string;
            value: string;
        };
        MarketplaceSellerDetails: {
            name: string;
        };
        PaymentProvider: {
            /** @enum {string} */
            provider: "stripe";
            supported_payment_methods: "card"[];
        };
        LineItem: {
            id: string;
            item: components["schemas"]["Item"];
            base_amount: number;
            discount: number;
            subtotal: number;
            tax: number;
            total: number;
            name?: string;
            description?: string;
            images?: string[];
            unit_amount?: number;
            disclosures?: components["schemas"]["Disclosure"][];
            custom_attributes?: components["schemas"]["CustomAttribute"][];
            marketplace_seller_details?: components["schemas"]["MarketplaceSellerDetails"];
        };
        Total: {
            /** @enum {string} */
            type: "items_base_amount" | "items_discount" | "subtotal" | "discount" | "fulfillment" | "tax" | "fee" | "total";
            display_text: string;
            amount: number;
            description?: string;
        };
        FulfillmentOptionShipping: {
            /** @constant */
            type: "shipping";
            id: string;
            title: string;
            subtitle?: string;
            carrier?: string;
            /** Format: date-time */
            earliest_delivery_time?: string;
            /** Format: date-time */
            latest_delivery_time?: string;
            subtotal: number;
            tax: number;
            total: number;
        };
        FulfillmentOptionDigital: {
            /** @constant */
            type: "digital";
            id: string;
            title: string;
            subtitle?: string;
            subtotal: number;
            tax: number;
            total: number;
        };
        SelectedShippingFulfillmentOption: {
            option_id: string;
            item_ids: string[];
        };
        SelectedDigitalFulfillmentOption: {
            option_id: string;
            item_ids: string[];
        };
        SelectedFulfillmentOption: {
            /** @enum {string} */
            type: "shipping" | "digital";
            shipping?: components["schemas"]["SelectedShippingFulfillmentOption"];
            digital?: components["schemas"]["SelectedDigitalFulfillmentOption"];
        } & ({
            /** @constant */
            type?: "shipping";
        } | {
            /** @constant */
            type?: "digital";
        });
        MessageInfo: {
            /** @constant */
            type: "info";
            /** @description RFC 9535 JSONPath */
            param?: string;
            /** @enum {string} */
            content_type: "plain" | "markdown";
            content: string;
        };
        MessageError: {
            /** @constant */
            type: "error";
            /** @enum {string} */
            code: "missing" | "invalid" | "out_of_stock" | "payment_declined" | "requires_sign_in" | "requires_3ds";
            /** @description RFC 9535 JSONPath */
            param?: string | null;
            /** @enum {string} */
            content_type: "plain" | "markdown";
            content: string;
        };
        Link: {
            /** @enum {string} */
            type: "terms_of_use" | "privacy_policy" | "return_policy";
            /** Format: uri */
            url: string;
        };
        PaymentData: {
            token: string;
            /** @enum {string} */
            provider: "stripe";
            billing_address?: components["schemas"]["Address"];
        };
        Order: {
            id: string;
            checkout_session_id: string;
            /** Format: uri */
            permalink_url: string;
        };
        CheckoutSessionBase: {
            id: string;
            buyer?: components["schemas"]["Buyer"];
            payment_provider?: components["schemas"]["PaymentProvider"];
            /** @enum {string} */
            status: "not_ready_for_payment" | "ready_for_payment" | "completed" | "canceled" | "in_progress";
            currency: string;
            line_items: components["schemas"]["LineItem"][];
            fulfillment_details?: components["schemas"]["FulfillmentDetails"];
            fulfillment_options: (components["schemas"]["FulfillmentOptionShipping"] | components["schemas"]["FulfillmentOptionDigital"])[];
            selected_fulfillment_options?: components["schemas"]["SelectedFulfillmentOption"][];
            totals: components["schemas"]["Total"][];
            messages: (components["schemas"]["MessageInfo"] | components["schemas"]["MessageError"])[];
            links: components["schemas"]["Link"][];
        };
        CheckoutSession: components["schemas"]["CheckoutSessionBase"];
        CheckoutSessionWithOrder: components["schemas"]["CheckoutSessionBase"] & {
            order: components["schemas"]["Order"];
        };
        CheckoutSessionCreateRequest: {
            buyer?: components["schemas"]["Buyer"];
            items: components["schemas"]["Item"][];
            fulfillment_details?: components["schemas"]["FulfillmentDetails"];
            affiliate_attribution?: components["schemas"]["AffiliateAttribution"];
        };
        CheckoutSessionUpdateRequest: {
            buyer?: components["schemas"]["Buyer"];
            items?: components["schemas"]["Item"][];
            fulfillment_details?: components["schemas"]["FulfillmentDetails"];
            selected_fulfillment_options?: components["schemas"]["SelectedFulfillmentOption"][];
        };
        CheckoutSessionCompleteRequest: {
            buyer?: components["schemas"]["Buyer"];
            payment_data: components["schemas"]["PaymentData"];
            affiliate_attribution?: components["schemas"]["AffiliateAttribution"];
        };
        IntentTrace: {
            /**
             * @description Reason for abandonment. This enum is extensible: servers SHOULD accept
             *     unrecognized values and treat them as "other" (see RFC Section 7.2).
             *     Validators SHOULD be configured for lenient enum handling.
             * @enum {string}
             */
            reason_code: "price_sensitivity" | "shipping_cost" | "shipping_speed" | "product_fit" | "trust_security" | "returns_policy" | "payment_options" | "comparison" | "timing_deferred" | "other";
            /** @description A generated summary of the specific objection or negotiation gap. */
            trace_summary?: string;
            metadata?: {
                [key: string]: string | number | boolean;
            };
        };
        CancelSessionRequest: {
            intent_trace?: components["schemas"]["IntentTrace"];
        };
        Error: {
            /** @enum {string} */
            type: "invalid_request" | "request_not_idempotent" | "processing_error" | "service_unavailable";
            /** @description Implementation-defined error code */
            code: string;
            message: string;
            /** @description RFC 9535 JSONPath (optional) */
            param?: string;
        };
    };
    responses: never;
    parameters: {
        Authorization: string;
        ContentType: string;
        AcceptLanguage: string;
        UserAgent: string;
        IdempotencyKey: string;
        RequestId: string;
        Signature: string;
        Timestamp: string;
        APIVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Echo of the request idempotency key */
                    "Idempotency-Key"?: string;
                    /** @description Echo of the request correlation id */
                    "Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionCompleteRequest"];
            };
        };
        responses: {
            /** @description Completed session with order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionWithOrder"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelSessionRequest"];
            };
        };
        responses: {
            /** @description Canceled session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Not cancelable (already completed/canceled) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
