/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agentic_checkout/webhooks/order_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive order lifecycle events
         * @description Merchants POST order events so ChatGPT can stay in sync with fulfillment-grade truth.
         *     Requests MUST be signed with an HMAC signature in the `Merchant-Signature` header.
         */
        post: operations["postOrderEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Refund: {
            /** @enum {string} */
            type: "store_credit" | "original_payment";
            amount: number;
        };
        EventDataOrder: {
            /** @constant */
            type: "order";
            checkout_session_id: string;
            /** Format: uri */
            permalink_url: string;
            /** @enum {string} */
            status: "created" | "manual_review" | "confirmed" | "canceled" | "shipped" | "fulfilled";
            refunds: components["schemas"]["Refund"][];
        };
        WebhookEvent: {
            /** @enum {string} */
            type: "order_create" | "order_update";
            data: components["schemas"]["EventDataOrder"];
        };
        Error: {
            /** @enum {string} */
            type: "invalid_request" | "processing_error" | "service_unavailable";
            code: string;
            message: string;
            param?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postOrderEvents: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC signature header (e.g., Merchant_Name-Signature) over the raw request body */
                "Merchant-Signature": string;
                "Request-Id"?: string;
                Timestamp?: string;
                "Content-Type": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /** @description Event accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                        request_id?: string;
                    };
                };
            };
            /** @description Bad payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
